python -m sepo.train_sepo \
    --model_id sepo/models/Qwen2.5-VL-3B-Instruct \
    --data_path sepo/data/RLAIF_Sample/DPO_format_for_Qwen/dpo.json \
    --image_folder sepo/data/RLAIF_Sample/DPO_format_for_Qwen/images \
    --output_dir sepo/output_sepo_test \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --freeze_vision_tower True \
    --freeze_llm False \
    --learning_rate 1e-5 \
    --save_strategy steps \
    --save_steps 1000 \
    --save_total_limit 1 \
    --logging_steps 1 \
    --report_to none \
    --lora_enable True \
    --lora_rank 8 \
    --lora_alpha 16 \
    --fp16 False \
    --bf16 True \
    --remove_unused_columns False \
    --ddp_find_unused_parameters False \
    --topk_ratio 0.2
