python -m sepo.train_sepo_v2 \
    --model_id sepo/models/Qwen2.5-VL-3B-Instruct \
    --data_path sepo/data/RLAIF_Sample/DPO_format_for_Qwen/dpo.json \
    --image_folder sepo/data/RLAIF_Sample/DPO_format_for_Qwen/images \
    --output_dir sepo/output_sepo_test \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --freeze_vision_tower True \
    --freeze_llm False \
    --learning_rate 1e-5 \
    --save_strategy steps \
    --max_steps 100 \
    --save_steps 400 \
    --save_total_limit 3 \
    --logging_steps 1 \
    --report_to none \
    --lora_enable False \
    --fp16 False \
    --bf16 True \
    --tf32 True \
    --weight_decay 0.1 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --remove_unused_columns False \
    --ddp_find_unused_parameters False \
    --topk_ratio 0.4
